### ISSUE TITLE
tap.exe package install --repository flag does not use https

### ISSUE THREAD

**Issue by joe-fague** [opentap/opentap#1326] opened 2023-10-25 00:14 UTC
**Describe the bug**

tap.exe package install does not use https when specified in package manager or --repository flag

**Environment (please complete the following information):**

 - OS:  Windows 10
 - OpenTAP Version 9.21.1

**To Reproduce**

1."C:\Program Files\Keysight\Test Automation\tap.exe" package install -v --version beta --dependencies --non-interactive --repository https://-------- ----

**Actual behavior**

The message "Downloading --- version 'xxx' from 'http://----'

**Expected behavior**

The message "Downloading ----- version 'xxx' from 'https://-------'
Note the http**s**

**Additional context**

occurs when package manager has a https path and --repository flag

**Comment by joe-fague** [comment] 2023-10-25 00:15
this is important because I have process centers that strictly only allow https addresses.  http get blocked, so they cannot download packages.

**Comment by rmadsen-ks** [comment] 2023-10-30 12:22
This is a problem that has to be fixed in 9.23. 

It is behaving as intended, but the problem is that this specific server responds with 
an old source url. On the public package server it is using HTTPS.

The solution is to ignore that url that the server responds with and just use whatever was used for connecting to the server in the first place.

**Closed** 2024-03-18 15:00 UTC
Labels: enhancement

**Comment by bogdan-achim** [comment] 2024-04-09 14:11
Verified in OpenTAP v9.24.0-beta.33

![image](https://github.com/opentap/opentap/assets/118886454/5b79b37b-7dcf-490f-93b5-eacfca0f4311)

**Comment by rmadsen-ks** [comment] 2024-04-10 11:40
You have to download a package that has been uploaded with http (hard to know) and then verify that it is downloaded using HTTPS.

**Comment by Razvan-Muresan** [comment] 2024-04-11 09:08
Verified on OpenTAP version 9.24.0-beta.34 
All downloads are done through https
