### ISSUE TITLE
Ensure when packages are referenced without a version that only the latest compatible version is used

### ISSUE THREAD

**Issue by bdirenzo-keysight** [opentap/opentap#440] opened 2022-03-08 22:19 UTC
For instance, if Developer's System is referenced, we should ensure the version installed is compatible with the OpenTAP nuget package referenced (especially when no version is defined).

**Comment by bdirenzo-keysight** [comment] 2022-03-08 22:19
@AsgerIversen FYI from our discussion

**Comment by AsgerIversen** [comment] 2022-03-08 22:48
Thanks @bdirenzo-keysight 

I think this is for senarios like this:
```xml
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="Current">
   ...

  <ItemGroup>
    <PackageReference Include="OpenTAP" Version="9.15" />
    <AdditionalOpenTapPackage Include="Developer's System" />
  </ItemGroup>
</Project>
```

In 9.17, a csproj like that seemingly would try to upgrade OpenTAP to 9.17, since version 9.17 of the `Developer's System` package is picked. I suspect this could be a regression.

**Comment by AsgerIversen** [comment] 2022-03-08 23:02
Here is a simpler way to reproduce. This seems like something you should be able to do without getting a bunch of warnings and errors.
```
C:\temp\test> ./tap package list -i
OpenTAP - 9.15.2+39e6c2a2 - installed 
C:\temp\test> ./tap package install "Developer's System"
Unable to find a version of 'Editor' package compatible with currently installed packages. Some installed packages may be upgraded.
Unable to find a version of 'Keysight Licensing' package compatible with currently installed packages. Some installed packages may be upgraded.
Unable to find a version of 'WPF Controls' package compatible with currently installed packages. Some installed packages may be upgraded.
Unable to find a version of 'Results Viewer' package compatible with currently installed packages. Some installed packages may be upgraded.
Unable to find a version of 'CSV' package compatible with currently installed packages. Some installed packages may be upgraded.
Updates available for:
 - OpenTAP: 9.15.2+39e6c2a2 -> 9.17.2+ae18c706
Unable to find a version of 'Timing Analyzer' package compatible with currently installed packages. Some installed packages may be upgraded.
Downloaded 'Visual Studio SDK' to 'C:\temp\test\PackageCache\Visual Studio SDK.1.1.7+1c882bca.TapPackage'. [649 ms]
Downloading [==============================] (100.00% | 2.85 MB of 2.85 MB)
Downloaded 'SDK' to 'C:\temp\test\PackageCache\SDK.9.15.2+39e6c2a2.Windows,Linux.TapPackage'. [2.51 s]
Downloaded 'PathWave Licensing' to 'C:\temp\test\PackageCache\PathWave Licensing.1.4.1+e5816333.x64.TapPackage'. [578 ms]
Downloaded 'Keysight Floating Licensing' to 'C:\temp\test\PackageCache\Keysight Floating Licensing.1.4.1+e5816333.TapPackage'. [1.09 s]
Downloaded 'Keysight Fixed Licensing' to 'C:\temp\test\PackageCache\Keysight Fixed Licensing.1.4.1+e5816333.TapPackage'. [369 ms]
Downloaded 'SQLite and PostgreSQL' to 'C:\temp\test\PackageCache\SQLite and PostgreSQL.9.4.2+3009aace.TapPackage'. [1.10 s]
Downloaded 'Timing Analyzer' to 'C:\temp\test\PackageCache\Timing Analyzer.9.17.0+3810d814.x64.TapPackage'. [1.14 s]
Downloaded 'CSV' to 'C:\temp\test\PackageCache\CSV.9.11.0+98498e58.Windows,Linux.TapPackage'. [212 ms]
Downloading [==============================] (100.00% | 3.30 MB of 3.30 MB)
Downloaded 'Results Viewer' to 'C:\temp\test\PackageCache\Results Viewer.9.17.0+3810d814.x64.TapPackage'. [1.31 s]
Downloaded 'WPF Controls' to 'C:\temp\test\PackageCache\WPF Controls.9.17.0+3810d814.TapPackage'. [810 ms]
Downloaded 'Keysight Licensing' to 'C:\temp\test\PackageCache\Keysight Licensing.1.0.0+8a228623.Windows,Linux.TapPackage'. [238 ms]
Downloading [==============================] (100.00% | 5.03 MB of 5.03 MB)
Downloaded 'OpenTAP' to 'C:\temp\test\PackageCache\OpenTAP.9.17.2+ae18c706.x64.TapPackage'. [1.50 s]
Downloaded 'OSIntegration' to 'C:\temp\test\PackageCache\OSIntegration.1.4.0+c70929ac.TapPackage'. [308 ms]
Downloading [==============================] (100.00% | 5.47 MB of 5.47 MB)
Downloaded 'Editor' to 'C:\temp\test\PackageCache\Editor.9.17.0+3810d814.x64.TapPackage'. [1.66 s]
Downloaded 'Developer's System' to 'C:\temp\test\PackageCache\Developer's System.9.17.0+3810d814.TapPackage'. [211 ms]
Installing to C:\temp\test
Uninstalled OpenTAP version 9.15.2+39e6c2a2. [43.7 ms]
Installed PathWave Licensing version 1.4.1+e5816333 [43.8 ms]
Installed Keysight Floating Licensing version 1.4.1+e5816333 [103 ms]
Installed Keysight Fixed Licensing version 1.4.1+e5816333 [19.8 ms]
Starting install step 'Packages/OpenTap/Tap.Upgrader.exe '
Succesfully ran install step  'Packages/OpenTap/Tap.Upgrader.exe '. [1.69 s]
Unable to load type 'OpenTap.Plugins.EventsSerializerPlugin' from 'C:\temp\test\OpenTap.dll'. Reason: 'Could not load type 'OpenTap.Plugins.EventsSerializerPlugin' from assembly 'OpenTap, Version=9.15.2.0, Culture=neutral, PublicKeyToken=null'.'.
Installed OpenTAP version 9.17.2+ae18c706 [1.91 s]
Package 'OpenTAP' contains possibly relevant plugins for next package installations. Searching for plugins.. [1.91 s]
Multiple assemblies of different versions named OpenTap exists
Multiple assemblies of different versions named OpenTap.Package exists
Multiple assemblies of different versions named tap exists
Multiple assemblies of different versions named OpenTap.Cli exists
Multiple assemblies of different versions named OpenTap.Plugins.BasicSteps exists
Skipping assembly 'Tap.Upgrader.Copy.exe'. Assembly name does not match the file name.
Failed to instantiate OpenTap.Package.IncludePackageDependencies+IncludePackageDependenciesData. Skipping plugin.
Aborting installation of remaining packages (use --force to override this behavior).

**Comment by Denrask** [comment] 2022-03-09 11:57
Conclusion of meeting with @AsgerIversen  and @alnlarsen is that we need to modify ResolveGraph logic to mainly be concerned with OpenTAP as an InstalledPackage and not resolve OpenTAP as the last package. There are still some concerns to be dealt with, as we don't know the package dependency hierarchy before we resolve down the hierarchy.

**Comment by alnlarsen** [comment] 2022-03-09 12:36
In the context of a package referenced in a .csproj file, the version of OpenTAP installed through NuGet will NEVER be upgraded (in versions 9.17.0 and newer). If the specified packages require an update, the build will fail with an error message.

**Comment by Denrask** [comment] 2022-03-10 08:19
My previous comment is actually not related to this issue. This issue is caused by KS8400 now specifying a specific version of dependencies instead of "any". But this issue is reintroduced by OpenTAP in current 9.17 release and we should look into this before it becomes a problem in 9.18.

**Comment by rmadsen-ks** [comment] 2022-04-19 14:32
This was fixed by not using "Any" in the Developer's System. In general, we recommend not using 'any' in bundle packages.

We dont need to fix this.

**Closed by rmadsen-ks** 2022-04-19 14:32 UTC
Labels: enhancement
