### ISSUE TITLE
Command ./tap package list -q returns wrong results

### ISSUE THREAD

**Issue by apantir** [opentap/opentap#736] opened 2022-08-05 13:46 UTC
**Environment (please complete the following information):**

OS: macOS x64 with version 12.5
OpenTAP version 9.18.4+7dec4717

**Steps To Reproduce**

1. Use command ./tap package list -q

2. Use command ./tap package list --quiet

**Actual Results**

When using the command **./tap package list -q** you get wrong results vs when you are using **./tap package list --quiet**

**Expected Results**

You should get the same results when using both commands **./tap package list -q** or **./tap package list --quiet**

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/110477118/183089797-b69ae83a-15bb-43d7-a826-a03514e1af92.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/110477118/183089824-e09bf871-831d-4827-8170-41bb6848e569.png)

**Comment by rmadsen-ks** [comment] 2022-08-05 14:21
This is a duplicate of #736

**Closed** 2022-08-05 14:21 UTC
Labels: bug
