### ISSUE TITLE
ScpiStep : Result Publish with Index Option in Regular Expression extraction.

### ISSUE THREAD

**Issue by darwinsubramaniam** [opentap/opentap#913] opened 2022-11-16 05:20 UTC
**Describe the bug**
![image](https://user-images.githubusercontent.com/4163586/202089294-05fdf231-4db3-42f8-b9f3-813d1ba1a8c1.png)

**Actual behavior**
Based on the image above the return value from the SCPI command returns a long string of data and each results has to be grouped using the regular expression. The CSV result listener does not guarantee the order of data.

**Expected behavior**

Is it possible to for result listener to obey? I do understand this is not possible as ResultListener runs in different thread if I am not mistaken. The Solution which I see is by adding an option of adding index to the matching group before pushing the data, so the user can somehow sort the data , if require by the index later from the CSV in this scenario.

I would love to make the contribution , but first love to get some confirmation if there is other alternative.

**Comment by darwinsubramaniam** [comment] 2022-11-16 06:07
https://github.com/opentap/opentap/compare/main...darwinsubramaniam:opentap:feature/BasicScpiStepRegexDataWithIndex?expand=1 - part of small POC solution

**Comment by rmadsen-ks** [comment] 2022-11-17 13:46
@darwinsubramaniam, I was not able to reproduce the issue with just a simple regular expression. Maybe the problem is also that I don't understand the regular expression you wrote in the issue and I don't really understand what your intention was.

**Comment by darwinsubramaniam** [comment] 2022-11-18 01:28
Hi @rmadsen-ks,

If you go to the link https://regex101.com/r/kFkIsB/1 , you will see _Test String_ **(Actual data send by the SCPI instrument)**  and the regex expression . The SCPI instrument data is a long string  and within the string there are 201 match using the regex expression . The ScpiStep now publishing each match by invoking the Result.Publish for 201 times. 
May I know how many matches found in your test? 
Plugin Used: 
- [ ] CSV Result Listener

**Comment by rmadsen-ks** [comment] 2024-05-23 17:14
I think the expressions feature + the feature to add outputs to scpi and run program step (#1233) makes this possible in a mor egeneric way.

I think we can close this.

**Closed by rmadsen-ks** 2024-05-23 17:14 UTC
Labels: Feature
