### ISSUE TITLE
Gitversion Macro incorrect calculation of precedence

### ISSUE THREAD

**Issue by joe-fague** [opentap/opentap#1321] opened 2023-10-19 23:56 UTC
**Describe the bug**

I’ve been experiencing the Gitversion macro calculating a number that is lower precedence than a version calculated in a previous commit.

[[ information omitted ]]
My expectation would be that the Gitversion precedence would be 133 < 134 < 135.  But what actually happened was 134 < 135 < 133

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.21.1

**To Reproduce**

1. Make a commit on branch A
2. make a new branch (B) off of branch A, make several commits on branch B
3. make another commit on branch A
4. Merge branch A into branch B
5. Merge branch B into branch A

**Actual behavior**

The Gitversion calculated on branch A of step 5 will be a smaller number (less precedence) than the Gitversion calculated on branch A of step 4

**Expected behavior**

The Gitversion calculated on branch A of step 5 should be bigger number (higher precedence) than the Gitversion calculated on branch A of step 4

**Comment by rmadsen-ks** [comment] 2023-10-23 13:33
Hi @joe-fague,

The way GitVersion is calculated is based on which branch is your main development branch and which are feature/alpha branches.

When you write you merge A into B and B into A, which one is your main development branch and which is your feature branch?

**Comment by joe-fague** [comment] 2023-10-23 16:30
my Gitversion file has "beta branch = develop"
Branch A in my example is develop
Branch B is a feature/x branch

repository: https://bitbucket.it.keysight.com/projects/SNPI/repos/kemoraet/browse

**Comment by rmadsen-ks** [comment] 2023-10-25 13:51
I tried creating a test project with this, but I was not able to reproduce the issue.
Develop = A branch, test = B branch.
```bat
del /S /Q .git
git init
git checkout -b develop
git add .gitversion
git commit -m "initialized" --allow-empty
git commit -m "integration" --allow-empty
call tap sdk gitversion
git checkout -b userdevelop 
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git checkout develop
git commit -m "integration2" --allow-empty
call tap sdk gitversion
git checkout userdevelop 
git merge develop
git checkout develop
call tap sdk gitversion
git merge userdevelop
call tap sdk gitversion
echo "Finished"
```

**Comment by joe-fague** [comment] 2024-01-04 18:47
![image](https://github.com/opentap/opentap/assets/148506063/b11beb03-9c70-4a01-9bc6-e998aa3c8313)
I've found a simpler reproduction of this bug.
commit 64b78ee2 calculates version OpenTap.Plugins.KemoraEt.1.10.0-beta.23+64b78ee2
commit 31fba335 calculates version OpenTap.Plugins.KemoraEt.1.10.0-beta.18+31fba335
both of these commits had a common commit at 5aa24441

maybe it has something to do with master branch merging into develop, and then a feature branch (originating from develop) merging back into develop?

**Comment by joe-fague** [comment] 2024-01-04 22:18
ok I have a script to reproduce my problem:

create an empty folder, paste this script as a .bat file.  run it twice.

`@echo off
del /S /Q .git
git init
git checkout -b master
git add .gitversion
git commit -m "initialized" --allow-empty
git commit -m "integration" --allow-empty
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
git checkout -b develop 
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
git checkout -b feature/f1
git commit -m "test" --allow-empty
git checkout develop 
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
git checkout master 
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
git checkout develop 
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
git merge master
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
git commit -m "test" --allow-empty
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
git checkout feature/f1
git merge develop
git commit -m "test" --allow-empty
git checkout develop
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
git merge feature/f1
call "C:\Program Files\Keysight\Test Automation\tap.exe" sdk gitversion
echo "Finished"
@echo on`

run it twice.  first execution output has no bug:
`0.0.1-beta.2+5ef86c40
0.0.1-beta.5+397e7876
0.0.1-beta.8+d752b7b4
0.0.1-alpha.1.7+1369213a.master
0.0.1-beta.8+d752b7b4
0.0.1-beta.9+c04de861
0.0.1-beta.13+289b1c4b
0.0.1-beta.13+289b1c4b
0.0.1-beta.14+34f41e7e`

2nd execution has the bug:
`0.0.1-beta.2+eeb99dcb
0.0.1-beta.5+c3474725
0.0.1-beta.8+84d8f493
0.0.1-alpha.1.7+1369213a.master
0.0.1-beta.8+84d8f493
0.0.1-beta.9+5720cdc4
0.0.1-beta.13+56833e6c
0.0.1-beta.13+56833e6c
0.0.1-beta.8+feafe3dc`

**Comment by joe-fague** [comment] 2024-01-04 22:28
in fact, running the above script, if i manually delete the .git folder after each execution, it appears random if the final print statement is 0.0.1-beta.14 or 0.0.1-beta.8.  it doesn't matter if a .gitversion file exists or not

**Comment by alnlarsen** [comment] 2024-01-17 09:43
Thanks for the script. I am able to reproduce this on Windows. Interestingly, it does not seem to reproduce on Linux.

**Comment by alnlarsen** [comment] 2024-01-17 10:30
@joe-fague the script you provided yields different results on Windows on different runs. This was surprising to me, but it looks like the way the Windows distribution of git determines merge strategies is not deterministic. (this is of course dependent on your ~/.gitconfig file). If I slightly tweak your script to include merge with `--no-ff`, the final version is `beta.14` every time.

I also looked into the way OpenTAP calculates the gitversion. It seems to be correct to me.
OpenTAP uses libgit to calculate the distance between two commits. A commit can have multiple parents. A merge commit has two parents: The head of the branch that was merged, and the commit that the branch  forked out from. In this case, we pick the first parent (the original branch point).

In order to see why the version becomes `beta.8`, we need to compare the logs for the two different merge strategies (see below)

When the version becomes beta.8, we see a merge commit near the top that points down to the last of the 7 "test" commits in the beginning of the script you provided. Adding the merge commit, we get a commit distance of 8.

I don't think this is something we can fix in OpenTAP. My recommendation would be to ensure you use a consistent merge strategy. Personally I prefer squashing

## git log for beta.8
```
commit 30f84ddcc555df64cec428495e87fdb5b264f849
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:58 2024 +0100

    test

commit 0cc43980ed7fcf7101af9dee419a4c4bb828c84d
Merge: 2363d67 4815315
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:58 2024 +0100

    Merge branch 'develop' into feature/f1

commit 4815315f5ff66860c3c1780763f712b298420daa
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:57 2024 +0100

    test

commit b4620f742981e2907e6a0e33c324719541f04be8
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:57 2024 +0100

    test

commit 6095f8253dec30585121a4746a6a0bd5b4d56960
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:57 2024 +0100

    test

commit 5baa1404878881403728e222f7e3897167288db2
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:56 2024 +0100

    test

commit 267c11d0ae764566f4ec94c0efedb5de28b87c2d
Merge: 972928b 3ebbdae
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:55 2024 +0100

    Merge branch 'master' into develop

commit 3ebbdae256721b45f10b497694f0ba90487aa588
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:54 2024 +0100

    test

commit 542845f47b2b61335e4c3ddbcfb2e6b7d635f927
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:54 2024 +0100

    test

commit 2b1734cc6ffc7384f8f64f1942b6892def56d976
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:54 2024 +0100

    test

commit 898bc40f4c02ab946044e653d63058609439d567
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:53 2024 +0100

    test

commit aa0f0b319e0f499ed0b79a48cb2fa48f1f670336
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:53 2024 +0100

    test

commit 17a137bff8462d98a7a5cc18433e25ae17c94ff3
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:53 2024 +0100

    test

commit 972928b3347c711b13dd79a96df8ccef4c137b6e
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:52 2024 +0100

    test

commit b20b7018e68c2c32a7dd1c77889f72b9b518b1a5
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:52 2024 +0100

    test

commit 38b3fc4e6224a2f60d122552c8f6cd28f8c31e31
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:52 2024 +0100

    test

commit 2363d673849b1d6fda11288304e992c3e33001eb
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:51 2024 +0100

    test

commit 6d1c72844bdbbd43b6f1bcbde010436ec5b3c969
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:51 2024 +0100

    test

commit 5e8153b8cd833465a1a0dbbb3ef9a8f7c24e0314
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:50 2024 +0100

    test

commit 24dbbf5aac276bfebfce753a4ed24cd09bc2885b
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:50 2024 +0100

    test

commit 4666b3ee57811eae003fecd6401d032d96479d9d
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:49 2024 +0100

    integration

commit def9b88e18e6d4f822de96764f16f8ffb9fb817d
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:43:49 2024 +0100

    initialized
```

## git log for beta.14
```
commit b04cd5be5e4e02b690d8576efae3ad8a995cea77
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:21 2024 +0100

    test

commit a038e2ada89dee77c9667c642af6206acca583ca
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:19 2024 +0100

    test

commit deefbba0fd493f4cb8d555787fa1ce4956805a8f
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:19 2024 +0100

    test

commit a82fd5d959d47d717c2c7cfeb224c83a9dcb20b9
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:19 2024 +0100

    test

commit 4f19dd4a8aee3dd01c8512406d678bcc7f436474
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:19 2024 +0100

    test

commit 9c46dcf79c07904232916c5b792ed0d6569b2245
Merge: b775b8b e5d7e87
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:18 2024 +0100

    Merge branch 'master' into develop

commit e5d7e87863675fbe97b9458e9cd4c0ba2b72369e
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:17 2024 +0100

    test

commit eb2dd3e85579eb83671ffa67c7e50f179096b570
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:16 2024 +0100

    test

commit 69779400f57abb05077d4997433425a79355cb43
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:16 2024 +0100

    test

commit 365fbaf493e5f74cd8c3042497e3ee79e58abce1
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:16 2024 +0100

    test

commit 9ed73caf6693023df0d17166c036b0f2cff23bc9
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:16 2024 +0100

    test

commit e1de652df0c343d8ac52759f301272202d7de5ec
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:16 2024 +0100

    test

commit b775b8b60ce8564bd4017d3c2d422001082420be
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:15 2024 +0100

    test

commit d29423a865e23af630af052ea2918840750d6327
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:14 2024 +0100

    test

commit 952a704b370c264499c8277ce26c2b7969a68105
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:14 2024 +0100

    test

commit 6bb6fffb5391021ff4d47d8dc95767c94ac8d738
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:13 2024 +0100

    test

commit 69b015cca2a960c5d22d02c93da8ad580b1a9854
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:13 2024 +0100

    test

commit 420bc6b7a59d6cfa863f2b16e4ef62c210a808de
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:13 2024 +0100

    test

commit 0a5a83ed798d0f0794ceba1edb5f162d312079ca
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:12 2024 +0100

    integration

commit cfc639bbf1b620b39c60470da0be3fd6d3a5c58b
Author: Alexander Larsen <alexander.larsen@keysight.com>
Date:   Wed Jan 17 10:54:12 2024 +0100

    initialized
```

**Comment by alnlarsen** [comment] 2024-01-17 12:51
@joe-fague the script you provided yields different git logs on Windows on different runs. This was surprising to me, but it looks like the way the Windows distribution of git determines merge strategies is not deterministic. (this is of course dependent on your ~/.gitconfig file). If I slightly tweak your script to include merge with `--no-ff`, the final version is `beta.14` every time.

I also looked into the way OpenTAP calculates the gitversion. As far as I can tell, there is nothing wrong with the current implementation. In short:

OpenTAP uses libgit to calculate the distance between two commits. A commit can have multiple parents. A merge commit has two parents: The original branch point, and the head of the branch that was merged. OpenTAP picks the first parent in cases where there are multiple options. For a merge commit, this is the original branch point, which gives us the shortest distance. This is preferable because we would otherwise increment the version once for every commit that was merged, instead of incrementing just once for the feature that was merged.

In order to see why the version becomes `beta.8`, we need to compare the logs for the two different merge strategies (see below)

When the version becomes beta.8, we see a merge commit near the top that points down to the last of the 7 "test" commits in the beginning of the script you provided. Adding the merge commit, we get a commit distance of 8. Given the how OpenTAP calculates this number, this is expected given the log, but not what we wanted.. Notice the merge commit message, though: `Merge branch 'develop' into `feature/f1`. It mentions merging `develop` into `feature/f1`, in the script, we merge `feature/f1` back into develop right after, but there is no merge commit reflecting that fact. Let's break down what actually happened:

 What actually happened is that `git` made a merge commit on our `feature/f1` branch, but when we tried to merge the `feature/f1` branch back into `develop`, git chose to fast forward the commits. `feature/f1` back onto develop.

| Command | Output |
|---------|--------|
| `git checkout feature/f1` | Enter feature branch |
| `git merge develop`       | Git created a merge commit |
| `git checkout develop`    | Enter develop branch |
| `git merge feature/f1`    | Git fast-forwarded the commits from feature branch onto develop |

We are now in a state where the develop branch has a bogus fast-forwarded merge commit which throws off the version calculation.
There is no way from this log for OpenTAP to calculate the correct version in this state, at least not with the method we currently use.

My recommendation to you would be to ensure you don't fast-forward when you merge into develop. Either do a proper merge commit with `git merge --no-ff <branch>`, or perform a squash with `git merge --squash <branch>`

Example logs:

## git log for beta.8
    ```
    commit 30f84ddcc555df64cec428495e87fdb5b264f849
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:58 2024 +0100

    test

    commit 0cc43980ed7fcf7101af9dee419a4c4bb828c84d
    Merge: 2363d67 4815315
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:58 2024 +0100

    Merge branch 'develop' into feature/f1

    commit 4815315f5ff66860c3c1780763f712b298420daa
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:57 2024 +0100

    test

    commit b4620f742981e2907e6a0e33c324719541f04be8
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:57 2024 +0100

    test

    commit 6095f8253dec30585121a4746a6a0bd5b4d56960
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:57 2024 +0100

    test

    commit 5baa1404878881403728e222f7e3897167288db2
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:56 2024 +0100

    test

    commit 267c11d0ae764566f4ec94c0efedb5de28b87c2d
    Merge: 972928b 3ebbdae
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:55 2024 +0100

    Merge branch 'master' into develop

    commit 3ebbdae256721b45f10b497694f0ba90487aa588
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:54 2024 +0100

    test

    commit 542845f47b2b61335e4c3ddbcfb2e6b7d635f927
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:54 2024 +0100

    test

    commit 2b1734cc6ffc7384f8f64f1942b6892def56d976
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:54 2024 +0100

    test

    commit 898bc40f4c02ab946044e653d63058609439d567
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:53 2024 +0100

    test

    commit aa0f0b319e0f499ed0b79a48cb2fa48f1f670336
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:53 2024 +0100

    test

    commit 17a137bff8462d98a7a5cc18433e25ae17c94ff3
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:53 2024 +0100

    test

    commit 972928b3347c711b13dd79a96df8ccef4c137b6e
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:52 2024 +0100

    test

    commit b20b7018e68c2c32a7dd1c77889f72b9b518b1a5
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:52 2024 +0100

    test

    commit 38b3fc4e6224a2f60d122552c8f6cd28f8c31e31
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:52 2024 +0100

    test

    commit 2363d673849b1d6fda11288304e992c3e33001eb
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:51 2024 +0100

    test

    commit 6d1c72844bdbbd43b6f1bcbde010436ec5b3c969
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:51 2024 +0100

    test

    commit 5e8153b8cd833465a1a0dbbb3ef9a8f7c24e0314
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:50 2024 +0100

    test

    commit 24dbbf5aac276bfebfce753a4ed24cd09bc2885b
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:50 2024 +0100

    test

    commit 4666b3ee57811eae003fecd6401d032d96479d9d
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:49 2024 +0100

    integration

    commit def9b88e18e6d4f822de96764f16f8ffb9fb817d
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:43:49 2024 +0100

    initialized
    ```

## git log for beta.14
    ```
    commit b04cd5be5e4e02b690d8576efae3ad8a995cea77
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:21 2024 +0100

    test

    commit a038e2ada89dee77c9667c642af6206acca583ca
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:19 2024 +0100

    test

    commit deefbba0fd493f4cb8d555787fa1ce4956805a8f
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:19 2024 +0100

    test

    commit a82fd5d959d47d717c2c7cfeb224c83a9dcb20b9
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:19 2024 +0100

    test

    commit 4f19dd4a8aee3dd01c8512406d678bcc7f436474
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:19 2024 +0100

    test

    commit 9c46dcf79c07904232916c5b792ed0d6569b2245
    Merge: b775b8b e5d7e87
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:18 2024 +0100

    Merge branch 'master' into develop

    commit e5d7e87863675fbe97b9458e9cd4c0ba2b72369e
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:17 2024 +0100

    test

    commit eb2dd3e85579eb83671ffa67c7e50f179096b570
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:16 2024 +0100

    test

    commit 69779400f57abb05077d4997433425a79355cb43
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:16 2024 +0100

    test

    commit 365fbaf493e5f74cd8c3042497e3ee79e58abce1
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:16 2024 +0100

    test

    commit 9ed73caf6693023df0d17166c036b0f2cff23bc9
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:16 2024 +0100

    test

    commit e1de652df0c343d8ac52759f301272202d7de5ec
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:16 2024 +0100

    test

    commit b775b8b60ce8564bd4017d3c2d422001082420be
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:15 2024 +0100

    test

    commit d29423a865e23af630af052ea2918840750d6327
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:14 2024 +0100

    test

    commit 952a704b370c264499c8277ce26c2b7969a68105
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:14 2024 +0100

    test

    commit 6bb6fffb5391021ff4d47d8dc95767c94ac8d738
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:13 2024 +0100

    test

    commit 69b015cca2a960c5d22d02c93da8ad580b1a9854
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:13 2024 +0100

    test

    commit 420bc6b7a59d6cfa863f2b16e4ef62c210a808de
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:13 2024 +0100

    test

    commit 0a5a83ed798d0f0794ceba1edb5f162d312079ca
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:12 2024 +0100

    integration

    commit cfc639bbf1b620b39c60470da0be3fd6d3a5c58b
    Author: Alexander Larsen <alexander.larsen@keysight.com>
    Date:   Wed Jan 17 10:54:12 2024 +0100

    initialized
    ```

**Closed** 2024-01-23 14:48 UTC
Labels: bug

**Comment by bogdan-achim** [comment] 2024-02-27 14:24
QA can't verify
