### ISSUE TITLE
ResultTableOptimizer and multiresult step timing issue

### ISSUE THREAD

**Issue by mimartinviita** [opentap/opentap#797] opened 2022-09-09 07:57 UTC
**Describe the bug**

ResultTableOptimizer gives an error when teststep produces multiple results in a short time in newer TAP versions. 9.16.4 does not have this error

Error either: InvalidOperationException: Collection was modified; enumeration operation may not execute _or_ ArrayTypeMismatchException: Source array type cannot be assigned to destination array type.

10:33:15.972  ResultProxy  ArrayTypeMismatchException: Source array type cannot be assigned to destination array type.
10:33:15.972  ResultProxy      at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
10:33:15.972  ResultProxy      at System.Array.CopyTo(Array array, Int32 index)
10:33:15.972  ResultProxy      at OpenTap.ResultTableOptimizer.<>c__DisplayClass1_0.<MergeTables>b__1(ResultColumn v, Int32 i)
10:33:15.972  ResultProxy      at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
10:33:15.972  ResultProxy      at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
10:33:15.972  ResultProxy      at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
10:33:15.972  ResultProxy      at OpenTap.ResultTableOptimizer.MergeTables(IReadOnlyList`1 tables)
10:33:15.972  ResultProxy      at OpenTap.ResultSource.PublishResultTableInvokable.Invoke(IResultListener a, WorkQueue queue)
10:33:15.973  ResultProxy  Exception caught at:
10:33:15.973  ResultProxy      at Void WorkerFunction()
10:33:15.973  ResultProxy      at Void Process()
10:33:15.973  ResultProxy      at Void processQueue()
10:33:15.973  ResultProxy      at Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)

**Environment (please complete the following information):**

 - OS: Windows 10
 - OpenTAP Version 9.18.5 and 9.18.4

**To Reproduce**

1. Have a step which produces multiple results in a loop
        public override void Run()
        {
            for(var i=0; i<10; i++)
            {
                Publish($"TestResult_bool_{i}", true, true, true);
                Publish($"TestResult_2bool_{i}", true, true, true);
                Publish($"TestResult_int_{i}", 1, 0, 2);
            }
        }

**Actual behavior**

One of three scenarios happens:

- passes without errors, 

- passes with log lines about ArrayTypeMismatchException: Source array type cannot be assigned to destination array type

- Plan errors with error about collection was modified

**Expected behavior**

Expected to pass without errors, as was with 9.16.4

**Additional context**

If some sleep time is added after result publish then issue resolves. 

10:52:43.618  TestPlan     InvalidOperationException: Collection was modified; enumeration operation may not execute.
10:52:43.618  ResultProxy      at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
10:52:43.618  ResultProxy      at System.Array.CopyTo(Array array, Int32 index)
10:52:43.618  ResultProxy      at OpenTap.ResultTableOptimizer.<>c__DisplayClass1_0.<MergeTables>b__1(ResultColumn v, Int32 i)
10:52:43.618  ResultProxy      at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
10:52:43.618  ResultProxy      at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
10:52:43.618  ResultProxy      at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
10:52:43.618  ResultProxy      at OpenTap.ResultTableOptimizer.MergeTables(IReadOnlyList`1 tables)
10:52:43.618  ResultProxy      at OpenTap.ResultSource.PublishResultTableInvokable.Invoke(IResultListener a, WorkQueue queue)
10:52:43.618  ResultProxy      at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
10:52:43.618  ResultProxy      at System.Array.CopyTo(Array array, Int32 index)
10:52:43.618  ResultProxy      at OpenTap.ResultTableOptimizer.<>c__DisplayClass1_0.<MergeTables>b__1(ResultColumn v, Int32 i)
10:52:43.618  ResultProxy      at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
10:52:43.618  ResultProxy      at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
10:52:43.618  ResultProxy      at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
10:52:43.618  ResultProxy      at OpenTap.ResultTableOptimizer.MergeTables(IReadOnlyList`1 tables)
10:52:43.618  ResultProxy      at OpenTap.ResultSource.PublishResultTableInvokable.Invoke(IResultListener a, WorkQueue queue)
10:52:43.618  ResultProxy  Exception caught at:
10:52:43.618  ResultProxy      at Void WorkerFunction()
10:52:43.618  ResultProxy      at Void Process()
10:52:43.618  ResultProxy      at Void processQueue()
10:52:43.618  ResultProxy      at Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
10:52:43.618  ResultProxy      ...
10:52:43.618  ResultProxy  Exception caught at:
10:52:43.618  ResultProxy      at Void WorkerFunction()
10:52:43.618  ResultProxy      at Void Process()
10:52:43.618  ResultProxy      at Void processQueue()
10:52:43.618  ResultProxy      at Void RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
10:52:43.618  ResultProxy      ...
10:52:43.618  TestPlan         at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
10:52:43.618  TestPlan         at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
10:52:43.618  TestPlan         at OpenTap.TestPlanRun.ScheduleInResultProcessingThread[T](IInvokable`2 r)
10:52:43.618  TestPlan         at OpenTap.ResultSource.Publish[T](T result)

**Comment by rmadsen-ks** [comment] 2022-09-09 11:12
Hi @mimartinviita, 

Thanks for submitting an issue!

I am not immediately able to reproduce the issue. I think because I don't have access to the code inside Publish.
If I do this everything seems to work:
```c#
                var xyz = new List<string> {"X", "Y", "Z"};
                for(var i=0; i<Count; i++)
                {
                    Results.Publish($"TestResult_bool_{i}", xyz, true, true, true);
                    Results.Publish($"TestResult_2bool_{i}", xyz,true, true, true);
                    Results.Publish($"TestResult_int_{i}",xyz, 1, 0, 2);
                }
```

Can you provide some information as to how your Publish method works?

**Comment by mimartinviita** [comment] 2022-09-12 06:47
Hi @rmadsen-ks 

Publish method just wraps the results into my own result object class to make similar. Seems like the problem occurs when publishing results through a class object. Also seems to be fixed when adding the Results.Wait() before each publish call. 

` public class MyResultClass<T> where T : IComparable
        {
            public MyResultClass(string resultName, T resultValue, T lowerLimit, T higherLimit, string unitOfResult,
            string comment)
            {
                ResultName = resultName;
                ResultValue = resultValue;
                LowerLimit = lowerLimit;
                HigherLimit = higherLimit;
                UnitOfResult = unitOfResult;
                Comment = comment;
            }

            public Verdict Verdict { get; set; }

            public string ResultName { get; set; }

            public string UnitOfResult { get; set; }

            public T ResultValue { get; set; }

            public T LowerLimit { get; set; }

            public T HigherLimit { get; set; }

            public string Comment { get; set; }

        }

        public override void Run()
        {
            
            for (var i=0; i<10; i++)
            {
                //Results.Wait();
                Results.Publish(new MyResultClass<bool>($"TestResult_bool_{i}", true, true, true, "NA", ""));
                //Results.Wait();
                Results.Publish(new MyResultClass<bool>($"TestResult_bool_{i}", true, true, true, "NA", ""));
                //Results.Wait();
                Results.Publish(new MyResultClass<int>($"TestResult_bool_{i}", 1, 0, 2, "NA", ""));
            }
        }`

**Comment by rmadsen-ks** [comment] 2022-09-12 07:39
@mimartinviita, thanks for your expanding the explaination.

I found the cause of the issue. It is due to the table name and the column names are they same. And they share ObjectType, (which is different from value type).

In this case, the table optimizer does not recognize the difference between
```
                // This:
                Results.Publish(new MyResultClass<bool>($"TestResult_bool_{i}", true, true, true, "NA", ""));
                // And this:
                Results.Publish(new MyResultClass<int>($"TestResult_bool_{i}", 1, 0, 2, "NA", ""));
```

It can be fixed by checking the ResultColumn.TypeCode when comparing table columns.

**Closed** 2022-09-13 12:17 UTC
Labels: bug
