### ISSUE TITLE
Uninstalling two packages at the same time displays the “Uninstalled” message only for one

### ISSUE THREAD

**Issue by AsgerIversen** [opentap/opentap#215] opened 2022-01-24 12:17 UTC
Originally filed January 19 2022 by Andrei Marincas on [GitLab](https://gitlab.com/OpenTAP/opentap/-/issues/832)

**Environment:**

Windows 10, 64-bit

OpenTAP 9.17.0-beta.8

**Steps to reproduce:**

1. Install OpenTAP 9.16.2
2. Upgrade to the 9.17.0-beta.8 by copying the package file into the OpenTAP folder and extract the archive there by replacing all the files
3. Open a command line in the OpenTAP folder
4. Install the Demonstration and the HTML5 packages
5. Uninstall the packages using the command: `tap package uninstall Demonstration HTML5`

**Actual result:**

Both packages are uninstalled but the “Uninstalled” message appears only for one

![2022-01-18_14_57_43-Windows_10_x64__Clean___Running__-_Oracle_VM_VirtualBox](https://gitlab.com/OpenTAP/opentap/uploads/267c094c426dd6ba6e9c750f0b6ea0f3/2022-01-18_14_57_43-Windows_10_x64__Clean___Running__-_Oracle_VM_VirtualBox.png)

**Expected result:**

The “Uninstalled”  message must appear for both packages

**Other remarks:**

**Comment by frederikja163** [comment] 2022-05-12 13:27
I could reproduce this from a 9.16 install but it seems to have been fixed in 9.17.2, as i could not reproduce for that version.

**Closed by frederikja163** 2022-05-12 13:27 UTC
Labels: good first issue, Regression

**Comment by razvancoste** [comment] 2022-05-13 06:54
Verified on 9.18.0-beta.16
![image](https://user-images.githubusercontent.com/98153555/168227863-bb3032f2-6d48-4efe-9dfb-f2b0f7ef0bc5.png)
