### ISSUE TITLE
Incompatible package RemoteSigntool is displayed in cmd

### ISSUE THREAD

**Issue by tiberiumuntean21** [opentap/opentap#615] opened 2022-05-27 12:14 UTC
**Environment:**
Windows 10, 64-bit
OpenTAP 9.18.0-alpha.1.1

**Steps to reproduce:**
1. Run the following command: tap package list RemoteSigntool -r "packages.opentap.keysight.com"

**Actual result:**
RemoteSigntool is displayed even if it's incompatible

![image](https://user-images.githubusercontent.com/98957694/170697207-bd25541c-2773-47f8-a77e-27f4a290c36f.png)

**Comment by Denrask** [comment] 2022-05-30 11:20
`RemoteSigntool` is incompatible due to its dependency on TAP Base: 
![image](https://user-images.githubusercontent.com/18167872/170981839-ef492598-f2d3-4122-9931-63426489134b.png)

**Comment by alnlarsen** [comment] 2022-09-02 11:28
I think the current behavior is correct. "compatibility" in the context of `tap package list` means CPU / platform compatibility, and not whether the package is compatible with the current installation.

@rmadsen-ks can we close this?

**Comment by alnlarsen** [comment] 2022-09-05 11:21
This is working as intended

**Closed by alnlarsen** 2022-09-05 11:21 UTC
Labels: bug
