### ISSUE TITLE
I can't install OpenTAP when I have installed a plugin with a missing dependency

### ISSUE THREAD

**Issue by apantir** [opentap/opentap#741] opened 2022-08-09 07:54 UTC
**Environment (please complete the following information):**

- OS: macOS x64 with version 12.5
- Reproduced on Windows 10
- OpenTAP version 9.18.4+7dec4717

**Steps to reproduce the behavior:**

1. Use command **./tap package install 'Vector Network Analyzer(v11)' --no-dependencies** or any other plugin with OpenTAP dependencies
2. Use command **./tap package install OpenTAP**

**Actual behavior**

You get dependencies log message about other Package 'Vector Network Analyzer(v11)' but OpenTAP doesn't have dependencies

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/110477118/183594530-58f3ba90-ce91-443e-b6f0-d7a3ad628a3b.png)

Log: [SessionLog 2022-08-09 10-51-26.txt](https://github.com/opentap/opentap/files/9288357/SessionLog.2022-08-09.10-51-26.txt)

**Expected behavior**

You should be able to install/reinstall OpenTAP

**Comment by rmadsen-ks** [comment] 2022-08-29 12:40
This is a known issue, but nevertheless we hope to be able to improve this in 9.19.

**Comment by alnlarsen** [comment] 2022-09-05 10:48
@rmadsen-ks will this be fixed by your resolver changes?

**Comment by alnlarsen** [comment] 2022-09-05 11:28
This is working as intended. `--no-dependencies` has been obsoleted. We do not want to promise full functionality in broken installations.

**Closed by alnlarsen** 2022-09-05 11:28 UTC
Labels: bug
